name       : python-pyserial
version    : 3.4
release    : 3
source     :
    - https://files.pythonhosted.org/packages/source/p/pyserial/pyserial-3.4.tar.gz : 6e2d401fdee0eab996cf734e67773a0143b932772ca8b42451440cfed942c627
license    : BSD-3-Clause
component  : programming.python
summary    : Python serial port access library
description: |
    This module encapsulates the access for the serial port. It
    provides backends for standard Python. The module named "serial"
    automaticaly selects the appropriate backend.
build      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
check      : |
    pushd $PKG_BUILD_DIR/py2build/test
        python run_all_tests.py
    popd

    pushd $PKG_BUILD_DIR/py3build/test
        python3 run_all_tests.py
    popd
