name       : python-pyserial
version    : '3.5'
release    : 7
source     :
    - https://files.pythonhosted.org/packages/source/p/pyserial/pyserial-3.5.tar.gz : 3c77e014170dfffbd816e6ffc205e9842efb10be9f58ec16d3e8675b4925cddb
license    : BSD-3-Clause
component  : programming.python
summary    : Python serial port access library
description: |
    This module encapsulates the access for the serial port. It
    provides backends for standard Python. The module named "serial"
    automaticaly selects the appropriate backend.
build      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
check      : |
    pushd $PKG_BUILD_DIR/py2build/test
        python run_all_tests.py
    popd

    pushd $PKG_BUILD_DIR/py3build/test
        python3 run_all_tests.py
    popd
