name       : python-pyserial
version    : 3.2.1
release    : 1
source     :
    - https://github.com/pyserial/pyserial/releases/download/v3.2.1/pyserial-3.2.1.tar.gz : 1eecfe4022240f2eab5af8d414f0504e072ee68377ba63d3b6fe6e66c26f66d1
license    : BSD-3-Clause
component  : programming.python
summary    : Python serial port access library
description: |
    This module encapsulates the access for the serial port. It
    provides backends for standard Python. The module named "serial"
    automaticaly selects the appropriate backend.
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    pushd test
    python3 run_all_tests.py
    popd
